### ISSUE TITLE
Patch divisibility logic fails when unique patch size value is same as check value

### ISSUE THREAD

**Issue by smcch** [mlcommons/GaNDLF#522]
**GaNDLF Version**
0.0.15

**Desktop (please complete the following information):**
 - OS: Windows 10 19044.2251

**How did you install GaNDLF**

git clone https://github.com/mlcommons/GaNDLF.git
cd GaNDLF
conda create -n venv_gandlf python=3.8 -y
conda activate venv_gandlf
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install -e .
python ./gandlf_verifyInstall

**Dataset description**

Radiology
MRI  3D  5 sequences 3 labels

**Describe your question/problem**

I'm trying to run a segmentation task but I get the following error when starting the process:

Constructing queue for validation data: 100%|██████████████████████████████████████ ███████| 8/8 [00:00<00:00, 42.54it/s]
Traceback (most recent call last):
  File "gandlf_run", line 100, in <module>
    main_run(
  File "C:\*********\GANDLF\cli\main_run.py", line 86, in main_run
    TrainingManager(
  File "C:\*********\GANDLF\training_manager.py", line 254, in TrainingManager
    training_loop(
  File "C:\*********\GANDLF\compute\training_loop.py", line 265, in training_loop
    ) = create_pytorch_objects(params, training_data, validation_data, device)
  File "C:\*********\GANDLF\compute\generic.py", line 68, in create_pytorch_objects
    model = get_model(parameters)
  File "C:\*********\GANDLF\models\__init__.py", line 110, in get_model
    return global_models_dict[params["model"]["architecture"]](parameters=params)
  File "C:\*********\GANDLF\models\unet.py", line 35, in __init__
    sys.exit(
TypeError: exit expected at most 1 argument, got 2

I follow your user guide and the parameters file "config_segmentation_brats.yaml" edited according to my requirements. Can you help me? 
Thanks

**Comment by smcch** [comment]
This is my folder structure:

/experiment_1/
	data_dir/
	model_dir/
	output_dir/
	model.yaml
	train.csv

the command line:
python gandlf_run -c ./experiment_1/model.yaml -i ./experiment_1/train.csv -m ./experiment_1/model_dir/ -t True -d cuda

**Comment by smcch** [comment]
model_dir:
- data_testing.pkl
- data_trainAndVal.pkl
- data_training.csv
- data_training.pkl
- data_validation.csv
- data_validation.pkl
- densenet_best.onnx
- densenet_best.pth
- logs_testing.csv
- logs_training.csv
- logs_validation.csv
- output_testing/
- output_validation/
- parameters.pkl

output_dir is empty
