### ISSUE TITLE
issues when installing from PyPI

### ISSUE THREAD

**Issue by hasan7n** [mlcommons/GaNDLF#629]
1. Following the documentation (https://mlcommons.github.io/GaNDLF/setup/#install-from-package-managers), trying to install using `pip install gandlf` gives the following error:
```
ERROR: Could not find a version that satisfies the requirement gandlf (from versions: 0.0.1, 0.0.16.dev0, 0.0.16.dev20230321, 0.0.16.dev20230322, 0.0.16.dev20230323, 0.0.16.dev20230324, 0.0.16.dev20230325, 0.0.16.dev20230326, 0.0.16.dev20230327, 0.0.16.dev20230328, 0.0.16.dev20230329, 0.0.16.dev20230330, 0.0.16.dev20230331, 0.0.16.dev20230401, 0.0.16.dev20230402, 0.0.16.dev20230403, 0.0.16.dev20230404, 0.0.16.dev20230405, 0.0.16.dev20230406, 0.0.16.dev20230407, 0.0.16.dev20230408, 0.0.16.dev20230409, 0.0.16.dev20230410, 0.0.16.dev20230411, 0.0.16.dev20230412, 0.0.16.dev20230413, 0.0.16.dev20230414, 0.0.16.dev20230415, 0.0.16.dev20230416, 0.0.16.dev20230417, 0.0.16.dev20230418, 0.0.16.dev20230419, 0.0.16.dev20230420, 0.0.16.dev20230421, 0.0.16.dev20230422, 0.0.16.dev20230423, 0.0.16.dev20230424, 0.0.16.dev20230425)
ERROR: No matching distribution found for gandlf
```
running `pip install gandlf==0.0.16.dev20230425`, for example, works.

2. Installing using `conda` doesn't seem to work. Took more than 10 minutes waiting for this:
```
Collecting package metadata (current_repodata.json): done
Solving environment: / 
```
Then I stopped it.

3. When installed using PyPI, `gandlf_deploy` doesn't work properly. I think it is because it tries to search for the Dockerfiles. The build context is being misconfigured (set to `/home/hasan_proj5/anaconda3/envs/gantest/lib/python3.8/site-packages` in my case)

**Comment by AlexanderGetka-cbica** [comment]
Regarding point 3: I am looking into this.

This issue arises from the fact that the structure of the repo and the structure of the installed package are different.
The Dockerfiles we use for CI/CD assume that the build context will be at the top level of the repo and that setup.py and all other files needed for installing the package will be available.
The installed package has only the GANDLF package itself.
I have been exploring a few options about this (basically, including these other files as data files) but haven't had luck -- they always end up in the wrong locations (too high up, in site-packages for example). I am trying a few things and will update on this. With some tweaking to setup.py this should be doable without needing duplicate Dockerfile templates.

**Comment by AlexanderGetka-cbica** [comment]
@hasan7n So I figured out a way to fix this, but in the course of that, came across a bug in what I guess is the MLCube runner?
My logs are below. I don't really know who to get in contact with, perhaps you know an easy workaround so I can test the deployment?

Basically the issue is that gandlf_deploy relies on "mlcube_docker configure" and passes -Prunner.build_strategy=always, so that the image will always get built (since obviously, if someone is deploying for a first time no image will exist to pull). But it seems like the MLCube runner is still trying to pull it... is this just a bug on that end or do we need to change the config that is being passed?

If we get an answer on this I think I will be done, then we can put that PR in and close this.


Running MLCube configuration with the following command:
mlcube_docker configure --platform=docker  -Prunner.build_strategy=always --mlcube=/home/agetka/work/GaNDLF/mlcube -Prunner.build_context=/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/GANDLF
If this is your first GaNDLF deployment, this may take longer than usual while image layers are built.
Error response from daemon: pull access denied for mlcommons/gandlf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
2023-05-09 11:05:49 SBIA-PC152 mlcube.shell[16657] ERROR Command='docker pull mlcommons/gandlf:0.0.1' status=256 exit_status=exited exit_code=1 on_error=raise
2023-05-09 11:05:49 SBIA-PC152 mlcube.__main__[16657] ERROR Failed to configure MLCube with error code 1.
Traceback (most recent call last):
  File "/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/mlcube_docker/docker_run.py", line 139, in configure
    Shell.run([docker, 'pull', image])
  File "/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/mlcube/shell.py", line 95, in run
    raise ExecutionError(
mlcube.errors.ExecutionError: Failed to execute shell command.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/mlcube/__main__.py", line 160, in configure
    runner.configure()
  File "/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/mlcube_docker/docker_run.py", line 146, in configure
    raise ExecutionError.mlcube_configure_error(self.__class__.__name__, description, **err.context)
mlcube.errors.ExecutionError: DockerRun runner failed to configure MLCube. Error occurred while pulling docker image (docker=docker, image=mlcommons/gandlf:0.0.1).
ERROR:
        message: DockerRun runner failed to configure MLCube.
        description: Error occurred while pulling docker image (docker=docker, image=mlcommons/gandlf:0.0.1).
        context: {'status': 'exited', 'code': 1, 'cmd': 'docker pull mlcommons/gandlf:0.0.1'}

**Comment by hasan7n** [comment]
It seems to me that it is not finding the Dockerfile. If you specify `build_strategy=always` but the dockerfile is missing from the build context, it tries to pull the image. Are you sure that the dockerfile is inside this folder `/home/agetka/work/GaNDLF/env_py38/lib/python3.8/site-packages/GANDLF` ?

**Comment by AlexanderGetka-cbica** [comment]
You're right that the issue is that the Dockerfiles (and other scripts needed for setup) can't be found in the properly installed package directory. I have made a workaround for that on my local branch, but when I run it, I run into the aforementioned issue, where it's attempting to pull "mlcommons/gandlf:0.0.1" and failing. Specifically I refer to these lines:

Error response from daemon: pull access denied for mlcommons/gandlf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
2023-05-09 11:05:49 SBIA-PC152 mlcube.shell[16657] ERROR Command='docker pull mlcommons/gandlf:0.0.1' status=256 exit_status=exited exit_code=1 on_error=raise

Does this happen in general when trying to configure MLCube now? Or is this somehow specific to us?

**Comment by AlexanderGetka-cbica** [comment]
Wait, I see what you mean. Checking something else now.

**Comment by AlexanderGetka-cbica** [comment]
OK, please see the above PR (#643). With these changes, it is working for me from a wheel-installed version, but I realize that this is something that will probably need more extensive testing. Let me know if any help is needed.
