### ISSUE TITLE
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with codebase

### ISSUE THREAD

**Issue by Linardos** [mlcommons/GaNDLF#641]
**GaNDLF Version**

0.0.16-dev

**Desktop (please complete the following information):**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

**How did you install GaNDLF**
Please provide all steps followed during installation.
# continue from previous shell
(venv_gandlf) $> git clone https://github.com/mlcommons/GaNDLF.git
(venv_gandlf) $> cd GaNDLF
(venv_gandlf) $> pip install -e .

**Dataset description**
histopathology data, 2D

**Describe your question/problem**
In the middle of training a classifier with GaNDLF, I got the following error:

AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with codebase

My config yaml includes this section which I assume it's what's referring to
version:
  maximum: 0.0.17
  minimum: 0.0.15
It seems my ganldf version (0.0.16) aligns with this requirements. Also it's rather odd that the error appears halfway through validation, as I'd expect an assertion error of this nature to appear immediately. Not sure what to make of it.

A bigger sample of the output error:

Looping over validation data:  59%|█████▉    | 7156/12145 [17:19<11:32,  7.20it/s]/cbica/home/linardop/.conda/envs/venv_gandlf/lib/python3.8/site-packages/tor
chio/data/image.py:131: UserWarning: Not specifying the image type is deprecated and will be mandatory in the future. You can probably use tio.ScalarImage or
tio.LabelMap instead
  warnings.warn(
Looping over validation data:  59%|█████▉    | 7157/12145 [17:19<11:35,  7.18it/s]Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code
base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with codebase

(the assertion error appeared a few more times before exiting)

**Comment by Linardos** [comment]
```python-traceback

Looping over validation data:  59%|█████▉    | 7156/12145 [17:19<11:32,  7.20it/s]/cbica/home/linardop/.conda/envs/venv_gandlf/lib/python3.8/site-packages/torchio/data/image.py:131: UserWarning: Not specifying the image type is deprecated and will be mandatory in the future. You can probably use tio.ScalarImage or tio.LabelMap instead
  warnings.warn(
Looping over validation data:  59%|█████▉    | 7157/12145 [17:19<11:35,  7.18it/s]Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2
Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 129, in <module>
    main_run(
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/cli/main_run.py", line 31, in main_run
    parameters = parseConfig(model_parameters)
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/GANDLF/parseConfig.py", line 117, in parseConfig
    assert (
AssertionError: The 'version' key needs to be defined in config with 'minimum' and 'maximum' fields to determine the compatibility of configuration with code base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cbica/home/linardop/The_Disentangled_Harmonization/src/GaNDLF/gandlf_run", line 140, in <module>
    sys.exit("Error in GANDLF run:", e)
TypeError: exit expected at most 1 argument, got 2

```
